version: '3.9'
services:
  mysql:
    hostname: mysql
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: gualdina2018
      MYSQL_DATABASE: userside
  userside:
    image: userside
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userside
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      USERSIDE_SERVERSIDE_WEATHER_PROVIDER_URL: http://serverside:8080/weather
    depends_on:
      - mysql
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: poison
      MONGO_INITDB_ROOT_PASSWORD: rats
  serverside:
    image: serverside
    ports:
      - "8081:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://poison:rats@mongo:27017/test
      WEATHER_API_URL: https://api.weatherapi.com/v1/current.json
      WEATHER_API_KEY: e4243250ab474b5b84c115932212710
    depends_on:
     - mongo